work_dir: outputs/train/fs26/v107--mnit_poselift_roboflow_satudora_veo3--r2.0-0xauto-1x1--satudora-filter-roi-conf--only-normal-satudora--1s-15frames--split-13-class

num_models: 10

# feeder
feeder: feeders.feeder_from_protogcn_format.Feeder
train_feeder_args:
  data_path: /home/laptq/ProtoGCN/outputs/convert_pkl_STGCN_to_ProtoGCN/fs26/mnit_poselift_roboflow_satudora_veo3--r2.0-0xauto-1x1--satudora-filter-roi-conf--only-normal-satudora--1s-15frames--split-13-class/train.pkl
  layout: "coco_onlyhand"
  split: train
  random_rot: False
  debug: False
  class_map: null

test_feeder_args:
  data_path: /home/laptq/ProtoGCN/outputs/convert_pkl_STGCN_to_ProtoGCN/fs26/shoplift25min_satudoraR9--r1-0x1-1x3--1s-15frames/val.pkl
  layout: "coco_onlyhand"
  split: val
  class_map: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]

# model
model: model.degcn.Model
model_args:
  num_class: 13
  num_point: 6
  num_person: 1
  base_frame: 15
  graph: graph.coco_onlyhand.Graph
  in_channels: 2
  k: 8
  eta: 4
  num_stream: 2
  graph_args:
    labeling_mode: 'spatial'


#optim
weight_decay: 0.0004
base_lr: 0.1
step: [10, 20, 30, 40]
warm_up_epoch: 2
cosine_epoch: 15

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 50
nesterov: True
